swiftmapper:
  datasource:
    url: jdbc:postgresql://localhost:5432/swiftmapper
    username: postgres
    password: 471979
    driver-class-name: org.postgresql.Driver
  migrations:
    location: db/migrations