package io.github.rocketbunny727.swiftmapper.dialect;

import io.github.rocketbunny727.swiftmapper.annotations.entity.GeneratedValue;
import io.github.rocketbunny727.swiftmapper.annotations.entity.Strategy;
import org.junit.jupiter.api.Test;

import java.lang.reflect.Field;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

class SqlDialectTest {

    @Test
    void resolvesDialectFromDriverBeforeExplicitConfigOrUrl() {
        SqlDialect dialect = SqlDialect.resolve(
                "mysql",
                "jdbc:postgresql://localhost:5432/app",
                "org.postgresql.Driver",
                "PostgreSQL"
        );

        assertEquals(SqlDialect.POSTGRESQL, dialect);
    }

    @Test
    void infersCommonJdbcDriversFromUrl() {
        assertEquals("org.postgresql.Driver",
                SqlDialect.inferDriverClassName("jdbc:postgresql://localhost/db").orElseThrow());
        assertEquals("com.mysql.cj.jdbc.Driver",
                SqlDialect.inferDriverClassName("jdbc:mysql://localhost/db").orElseThrow());
        assertEquals("org.sqlite.JDBC",
                SqlDialect.inferDriverClassName("jdbc:sqlite:file.db").orElseThrow());
    }

    @Test
    void rendersIdentifierQuotingPerDialect() {
        assertEquals("\"users\"", SqlDialect.POSTGRESQL.quoteIdentifier("users"));
        assertEquals("`users`", SqlDialect.MYSQL.quoteIdentifier("users"));
        assertEquals("[users]", SqlDialect.SQLSERVER.quoteIdentifier("users"));
        assertEquals("[dbo].[users]", SqlDialect.SQLSERVER.quoteIdentifier("dbo.users"));
    }

    @Test
    void rendersPagingPerDialect() {
        assertEquals(
                "SELECT * FROM users LIMIT 10 OFFSET 20",
                SqlDialect.POSTGRESQL.applyLimitOffset("SELECT * FROM users", 10, 20)
        );
        assertEquals(
                "SELECT * FROM users ORDER BY (SELECT NULL) OFFSET 20 ROWS FETCH NEXT 10 ROWS ONLY",
                SqlDialect.SQLSERVER.applyLimitOffset("SELECT * FROM users", 10, 20)
        );
        assertEquals(
                "SELECT * FROM users OFFSET 20 ROWS FETCH NEXT 10 ROWS ONLY",
                SqlDialect.ORACLE.applyLimitOffset("SELECT * FROM users", 10, 20)
        );
    }

    @Test
    void rendersIdentityAndSequenceSqlForPostgres() throws NoSuchFieldException {
        Field id = DialectEntity.class.getDeclaredField("id");
        GeneratedValue generatedValue = id.getAnnotation(GeneratedValue.class);

        assertEquals(
                "\"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
                SqlDialect.POSTGRESQL.idColumnDefinition("id", id.getType(), generatedValue)
        );
        assertEquals(
                "CREATE SEQUENCE \"users_id_seq\" START WITH 42 INCREMENT BY 1 NO MINVALUE NO MAXVALUE OWNED BY \"users\".\"id\"",
                SqlDialect.POSTGRESQL.createSequenceSql("users_id_seq", "users", "id", 42)
        );
        assertTrue(SqlDialect.POSTGRESQL.nextSequenceValueSql("users_id_seq").contains("nextval"));
    }

    private static class DialectEntity {
        @GeneratedValue(strategy = Strategy.IDENTITY)
        private Long id;
    }
}
